### ISSUE TITLE
commentAllowed is missing in the LNURLPayParams type

### ISSUE THREAD

**Issue by pseudozach** [fiatjaf/js-lnurl#1]
typescript does not like that.

**Comment by fiatjaf** [comment]
Why do you say that?

https://github.com/fiatjaf/js-lnurl/blob/005f736c7d1e1e2be174b126aa81fbdc248119a9/src/types.ts#L43

**Comment by pseudozach** [comment]
that's weird
I have  "js-lnurl": "^0.2.5",
and I don't see it. 

![Screen Shot 2021-12-16 at 8 28 37 AM](https://user-images.githubusercontent.com/3731591/146410344-cbb0d563-9da4-4b7b-89c9-90cffa41ed94.png)

**Comment by fiatjaf** [comment]
Get `0.3.0`. Should be good.
